import os
import sys
import subprocess

# Ensure we have the right number of arguments
if len(sys.argv) != 2:
    print("Usage: python run_and_process.py <LOCAL_IMAGE_PATH>")
    sys.exit(1)

LOCAL_IMAGE_PATH = sys.argv[1]
TEXT_PROMPT = "shirt"

# Check if the image exists
if not os.path.isfile(LOCAL_IMAGE_PATH):
    print(f"Image file does not exist: {LOCAL_IMAGE_PATH}")
    sys.exit(1)

# Extract the base filename without extension
base_filename = os.path.splitext(os.path.basename(LOCAL_IMAGE_PATH))[0]

# Define the output directory and ensure it exists
output_dir = './output'
os.makedirs(output_dir, exist_ok=True)

# Step 1: Run the run.py script with the image and text prompt ("shirt")
run_command = [
    "python", "run.py", LOCAL_IMAGE_PATH, TEXT_PROMPT
]
print(f"Running: {' '.join(run_command)}")

try:
    subprocess.run(run_command, check=True)
    print("run.py completed successfully.")
except subprocess.CalledProcessError as e:
    print(f"run.py failed: {e}")
    sys.exit(1)

# Step 2: Define the mask filename generated by run.py
mask_filename = f"{base_filename}_mask.png"
mask_image_path = os.path.join(output_dir, mask_filename)

# Check if the mask was created
if not os.path.isfile(mask_image_path):
    print(f"Mask file was not created: {mask_image_path}")
    sys.exit(1)

# Step 3: Run the process.py script with the image and output path
final_output_path = os.path.join(output_dir, f"{base_filename}_final.png")

process_command = [
    "python", "process.py", LOCAL_IMAGE_PATH, final_output_path
]
print(f"Running: {' '.join(process_command)}")

try:
    subprocess.run(process_command, check=True)
    print(f"process.py completed successfully. Masked image saved at: {final_output_path}")
except subprocess.CalledProcessError as e:
    print(f"process.py failed: {e}")
    sys.exit(1)

# Step 4: Run the cv_square.py script to crop the transparent margins of the final image
cv_square_command = [
    "python", "cv_square.py", final_output_path
]
print(f"Running: {' '.join(cv_square_command)}")

try:
    subprocess.run(cv_square_command, check=True)
    print(f"cv_square.py completed successfully. Cropped image saved at: {final_output_path}")
except subprocess.CalledProcessError as e:
    print(f"cv_square.py failed: {e}")
    sys.exit(1)
